### ISSUE TITLE
PyPi only rendering first line of long_description

### ISSUE THREAD

**Issue by gdude2002** [pypa/readme_renderer#59] opened 2018-01-04 18:29 UTC
Yesterday, I published the [initial alpha of my project](https://pypi.org/project/melcloud/0.0.1/) on PyPi. This release has a correctly-rendered description.

Today, I made some additions to the README and now PyPi is only rendering the first line in the file, regardless of what's actually there.

* [Current PyPi Release](https://pypi.org/project/melcloud/0.0.3/)
* [Current README](https://github.com/gdude2002/melcloud/blob/master/README.rst)

I've checked my README both with `readme_renderer` via `setup.py check -r -s` and also using `restview`, and everything seems to be just fine. I'm using Python `3.6.1` when checking that way. Additionally, GitHub appears to be perfectly happy with the README.

Is this a bug, or did I miss something obscure?

---

EDIT: `rstcheck` finds no errors either.

**Comment by di** [comment] 2018-01-04 19:08
Hi @gdude2002, thanks for the report. Could you tell us how you uploaded your distribution to PyPI?

**Comment by gdude2002** [comment] 2018-01-04 19:08
@di Yup - Simple enough really, I just ran `python3 setup.py sdist bdist_wheel` and `twine upload dist/*`.

**Comment by di** [comment] 2018-01-04 20:34
@gdude2002 I built an sdist of your package on my machine and uploaded it and and the README was correctly rendered using:

```
$ twine --version
twine version 1.9.1 (pkginfo: 1.4.1, requests: 2.18.4, setuptools: 38.2.4,
requests-toolbelt: 0.8.0, tqdm: 4.19.4)
```

However when I try to upload your original sdist at https://pypi.org/project/melcloud/0.0.3/#files, I can reproduce your issue, so it seems the issue is with how the sdist is built.

One difference I'm noticing is that there's Window's-style linebreaks (`^M`) in the `PKG-INFO` file of your sdist, and that the included `README.RST` is "ASCII text, with CRLF line terminators" (meaning windows/dos-style).

I'm thinking this is the reason you're having trouble and I'm not, since I'm not on a Windows machine. I also see this rather old bug report which hints at this being problematic: https://bugs.python.org/issue19549

Unfortunately I'm not very familiar with Windows, but I am guessing that this isn't an issue for other package maintainers who are using Windows. Maybe @pfmoore has an idea?

**Comment by gdude2002** [comment] 2018-01-04 20:38
Hmm, that's interesting. I just checked and my `setuptools` is a couple versions behind yours - I'll try updating it and build another sdist.

PyCharm allows me to convert line endings as well, so I'll see if that makes any difference with the README.

**Comment by gdude2002** [comment] 2018-01-04 20:39
Updating `setuptools` and writing my `README.rst` file using unix-style line-endings appears to have solved the problem.

I can't help but feel like the line endings shouldn't cause this problem, though.

**Comment by di** [comment] 2018-01-04 20:46
> PyPi doesn't render the top header, but I'm assuming this is intentional.

Yes, this is intentional.

> I can't help but feel like the line endings shouldn't cause this problem, though.

Agreed. Looking a little deeper it seems like the blame lies on `pkginfo` (which `twine` uses):

```py
>>> import pkginfo
>>> pkginfo.SDist('melcloud-0.0.3.tar.gz').description
"This is a module providing access to Mitsubishi's `MELCloud <https://www.melcloud.com/>`_ API."
```

Going to close this since you've resolved it and it's definitely not an issue with `readme_renderer`. Perhaps this should be raised over at the [pkginfo issue tracker](https://code.launchpad.net/~tseaver/pkginfo/trunk) instead?

**Closed by di** 2018-01-04 20:46 UTC

**Comment by gdude2002** [comment] 2018-01-04 21:45
Aw man, Launchpad? Guess it's time to add to my ever-growing list of accounts..

**Comment by tseaver** [comment] 2018-08-18 16:44
As I noted on the [LP bug](https://bugs.launchpad.net/pkginfo/+bug/1741352):

> The "body" part of the 'METADATA' file is returned by ['email.parser.Parser.get_payload'](https://bazaar.launchpad.net/~tseaver/pkginfo/trunk/view/head:/pkginfo/distribution.py#L139). 'pkginfo' does no other handling of it.
